/* 
    *@author:Naveen Kumar,
    *@createdDate:03/10/2020

*/


import * as mongoose from 'mongoose'; //importing headers
import * as MUUID from 'uuid-mongodb';

const Schema = mongoose.Schema;
const now = new Date();

const schema = new Schema({ //defining schemas
    userName: {
        type: String,
        required: true, //required feild
        trim: true //to remove white spaces
    },
    email: {
        type: String,
        unique: true, //Unique for all different users
        required: true,
        trim: true
    },
    hash: {
        type: String,
        required: true,
        trim: true
    },
    userRole: {
        type: String,
        required: true,
        enum: ['Admin', 'Manager', 'Assistant'],
        trim: true
    },
    phoneNo: {
        type: String,
        trim: true //to remove white spaces
    },
    salary: {
        type: Number,
        trim: true //to remove white spaces
    },
    createdDate: {
        type: Date, //Date type
        default: Date.now //To store the created date and time of the data
    },
    id: {
        type: String, //id generated by uuid npm inorder to better access of 
        default: () => MUUID.v1().toString(),
        unique: true
    }
})

schema.set('toJSON', {
    virtuals: true
});

module.exports = mongoose.model('User', schema);